version: "3"
services:
  ofetherconverter:
    build: .
    restart: always
    ports:
      - 8085:80
    volumes:
      - ./HRConvert2/config.php:/var/www/html/config.php
      - ./HRConvert2/Logs:/var/www/html/Logs
